name: Deploy Next.js with Terraform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd my-portfolio
        npm install

    - name: Build Next.js application
      run: |
        cd my-portfolio
        npm run build

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Terraform Init
      run: |
        cd my-portfolio
        terraform init

    - name: Terraform Plan
      run: |
        cd my-portfolio
        terraform plan -out=tfplan

    - name: Terraform Apply
      run: |
        cd my-portfolio
        terraform apply -auto-approve tfplan
