name: Deploy Next.js with Terraform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run:
        npm install

    - name: Build Next.js application
      run:
        npm run build

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "peiyuan3@illinois.edu"
        git config --global user.name "realbj-dot"
        git checkout --orphan gh-pages
        git rm -rf .
        
        mv build/* .
        rm -rf build
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push -f origin gh-pages